### ISSUE TITLE
ShittyImageCropVC not showing anything

### ISSUE THREAD

**Issue by kamalupasena** [budidino/ShittyImageCrop#2]
after i call ShittyImageCrop its not showing anything in the view , can you help me to fixed this ?

![img_0158](https://user-images.githubusercontent.com/5517484/26975745-b96e9eb0-4d3e-11e7-9e4c-f1d92e6a4fa7.PNG)

**Comment by srector13** [comment]
You have to add the image assets that the VC uses for buttons and name your image correctly. The button names it looks for are crop-back and crop-checkmark. The image name its looking for to display is img. Either download the assets in this project and add them to yours or rename the variables in the VC. Once you do that the image and the two buttons will display correctly.

**Comment by kidvicious** [comment]
Same thing happened to me. I downloaded your project and the result is the same. the crop-back and crop-checkmark buttons are showing but the imageView is blank.

**Comment by carlosmouracorreia** [comment]
Same here

**Comment by budidino** [comment]
Sorry guys for super late reply. The code was updated and should work now. Sorry for the inconvenience and thank you all for reporting the issue.
